### ISSUE TITLE
spit-specs conflates ns with prefix

### ISSUE THREAD

**Issue by solussd** [paren-com/serene#7]
The file generated by spit-specs uses the prefix as the file's namespace. I've been having to manually change the namespace in the generated file (it's location-derived namespace is quite long and I don't want my spec prefixes to match it).

Could ns be a separate option to spit-specs?

**Comment by domkm** [comment]
The input to `spit-specs` is `file`, `ns`, `schema`, and, optionally, compiler options `xform`. It does not take the prefix as input. As with `def-specs`, the prefix defaults to the namespace in which the specs are defined but can be aliased so something more convenient using the `:prefix` compiler option.
